plugins { id 'com.android.application' }

android {
    namespace 'com.mizandar.matrixevreni'
    compileSdk 36

    signingConfigs {
        cleanDebug {
            storeFile file('matrixevreni-clean.jks')
            storePassword 'varantmatik'
            keyAlias 'varantmatik-lite'
            keyPassword 'varantmatik'
        }
    }

    defaultConfig {
        applicationId 'com.mizandar.matrixevreni.cleanv11'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1-clean'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.cleanDebug
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.cleanDebug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
